# Generated by Django 4.2.13 on 2024-06-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_alter_mockmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockmodel',
            name='res',
            field=models.JSONField(blank=True, null=True, unique=True),
        ),
    ]
