# Generated by Django 4.2.13 on 2024-06-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_alter_mockmodel_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockmodel',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mockmodel',
            name='res',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
