# Generated by Django 4.2.13 on 2024-06-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='acitivate',
        ),
    ]
