# Generated by Django 4.2.13 on 2024-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_username_usertoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
